USE SUCOS;

ALTER TABLE tbcliente ADD PRIMARY KEY (CPF);

ALTER TABLE tbcliente ADD COLUMN (DATA_NASCIMENTO DATE);
ALTER TABLE sucos.tbcliente DROP COLUMN DATA_NASCIMENTO;

INSERT INTO tbcliente(
CPF, NOME, ENDERECO1, ENDERECO2, IDADE, SEXO, LIMITE_CREDITO, VOLUME_DE_COMPRA_SUCOS, PRIMEIRA_COMPRA,
DATA_NASCIMENTO)
VALUES ('0851865907','LUCAS BENINCA','DOIS VIZINHOS PR RUA DO COMÉRCIO','',25,'M',5000.00,1000,0,
'2021-09-02'
);