CREATE TABLE tbCliente 
(CPF VARCHAR(12),
NOME VARCHAR(100),
ENDERECO1 VARCHAR(150),
ENDERECO2 VARCHAR(150),
DATA_NASCIMENTO SMALLINT,
IDADE SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUME_DE_COMPRA_SUCOS FLOAT,
PRIMEIRA_COMPRA BIT(1));

CREATE TABLE tb_Vendedores
(MATRICULA VARCHAR(5),
NOME VARCHAR(100),
PERCENTUAL_COMISSAO FLOAT);

CREATE TABLE tb_Produtos(
PRODUTO VARCHAR(100),
NOME VARCHAR(150),
EMBALAGEM VARCHAR(50),
TAMANHO VARCHAR(50),
SABOR VARCHAR(50),
PRECO_LISTA FLOAT);


